# Generated by Django 3.1.7 on 2021-04-05 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analiticos', '0002_auto_20210405_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='Archivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analiticos.archivo'),
        ),
        migrations.DeleteModel(
            name='Excel',
        ),
    ]
